name: dApp upload to IPFS

permissions:
  contents: read

on:
  push:
    branches: [dapp_production]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ipds:
    name: Publish dApp on IPFS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    environment:
      name: dapp-ipfs
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v6

      - name: Install App dependencies
        run: npm install

      - name: Build app
        env:
          PUBLIC_STELLAR_NETWORK_PASSPHRASE: ${{ vars.PUBLIC_STELLAR_NETWORK_PASSPHRASE }}
          PUBLIC_STELLAR_RPC_URL: ${{ vars.PUBLIC_STELLAR_RPC_URL }}
          PUBLIC_PUBLIC_STELLAR_HORIZON_URL: ${{ vars.PUBLIC_PUBLIC_STELLAR_HORIZON_URL }}
        run: npm run build

      - name: Generate artifact attestation for dist
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a
        with:
          subject-path: "./dist/*"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v5
        with:
          name: dist
          path: |
            ./dist/*

      - uses: storacha/add-to-web3@892505d8e70c79336721485e5500155c17a728e0
        id: storacha
        with:
          path_to_add: "./dist"
          secret_key: ${{ secrets.STORACHA_PRINCIPAL }}
          proof: ${{ secrets.STORACHA_PROOF }}

      - name: Job summary
        run: |
          echo "### Shipping to IPFS! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- CID: ${{ steps.storacha.outputs.cid }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- URL: ${{ steps.storacha.outputs.url }}" >> "$GITHUB_STEP_SUMMARY"
